"""Small, dependency-free representations used by scientific campaigns."""

from acfqp.science.latent_resource_2048_v1 import (
    RAW_FEATURE_NAMES_V1,
    RAW_VECTOR_DIMENSION_V1,
    RESOURCE_FEATURE_NAMES_V1,
    RESOURCE_VECTOR_DIMENSION_V1,
    STATE_ONLY_RESOURCE_FEATURE_NAMES_V1,
    STATE_ONLY_RESOURCE_VECTOR_DIMENSION_V1,
    Standard2048KnownModelLatentResourceRepresentationV1,
    Standard2048LatentResourceRepresentationV1,
    Standard2048StateOnlyLatentResourceRepresentationV1,
    encode_standard_2048_board_v1,
    encode_standard_2048_known_model_board_v1,
    encode_standard_2048_known_model_state_v1,
    encode_standard_2048_state_only_board_v1,
    encode_standard_2048_state_only_state_v1,
    encode_standard_2048_state_v1,
    known_model_resource_standard_2048_vector_v1,
    raw_standard_2048_vector_v1,
    resource_standard_2048_vector_v1,
    state_only_resource_standard_2048_vector_v1,
)

__all__ = (
    "RAW_FEATURE_NAMES_V1",
    "RAW_VECTOR_DIMENSION_V1",
    "RESOURCE_FEATURE_NAMES_V1",
    "RESOURCE_VECTOR_DIMENSION_V1",
    "STATE_ONLY_RESOURCE_FEATURE_NAMES_V1",
    "STATE_ONLY_RESOURCE_VECTOR_DIMENSION_V1",
    "Standard2048KnownModelLatentResourceRepresentationV1",
    "Standard2048LatentResourceRepresentationV1",
    "Standard2048StateOnlyLatentResourceRepresentationV1",
    "encode_standard_2048_board_v1",
    "encode_standard_2048_known_model_board_v1",
    "encode_standard_2048_known_model_state_v1",
    "encode_standard_2048_state_only_board_v1",
    "encode_standard_2048_state_only_state_v1",
    "encode_standard_2048_state_v1",
    "known_model_resource_standard_2048_vector_v1",
    "raw_standard_2048_vector_v1",
    "resource_standard_2048_vector_v1",
    "state_only_resource_standard_2048_vector_v1",
)
