"""Signed, exact, streaming observation batches for V0-075.

This authority replaces one public record and RSA signature per draw with one
signed aggregate over a contiguous accepted-draw interval.  Samples are still
generated by the same :class:`DeterministicH2GraphStreamV1`; aggregation is
streaming and therefore changes neither the tape nor exact arithmetic.

Public artifacts contain outcome counts, exact reward sums, failure/terminal
counts, random-word/rejection accounting, and a deterministic hash-chain
commitment to every underlying sample.  They contain no law, salt, kernel,
random seed, or individual random word.

Production and construction authority paths are exact-type separated.
Independent private replay regenerates the interval from the beginning and
compares the complete aggregate without serializing private material.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from fractions import Fraction
import hashlib
from typing import TYPE_CHECKING, Any, Iterable, Mapping

from acfqp.h2_graph_transition_engine_v1 import (
    DeterministicH2GraphStreamV1,
    H2GraphActionV1,
    H2GraphKernelV1,
    H2GraphSampleV1,
    H2GraphTransitionInvariantViolation,
)
from acfqp.phase3e_ids import (
    Phase3EIdentityError,
    canonical_json_bytes,
    loads_canonical_json,
    parse_content_id,
)
from acfqp import v075_private_environment_generation_profile_v1 as private_env
from acfqp import v075_private_observer_boundary_v1 as observer
from acfqp import v075_public_campaign_authority_v1 as public
from acfqp import v075_public_graph_semantics_v1 as graph

if TYPE_CHECKING:
    from acfqp.v075_remote_main_anchor_verifier_v1 import (
        V075ProductionOpenAuthorityV1,
    )


SCHEMA_VERSION = "1.0.0"
PROPOSED_CONTRACT_VERSION = "1.40.0"
PROFILE_KEY = "v075_signed_batched_observer_authority_v1"

MAX_ACCEPTED_DRAW_CAP = 25_000_000
MAX_BATCH_ACCEPTED_DRAW_COUNT = 25_000_000
MAX_CANONICAL_BATCH_BYTES = 16 * 1024 * 1024

TRANSCRIPT_INITIAL_DOMAIN = (
    b"acfqp:v075-batched-observation-transcript-initial:v1"
)
TRANSCRIPT_LEAF_DOMAIN = (
    b"acfqp:v075-batched-observation-transcript-leaf:v1"
)
TRANSCRIPT_STEP_DOMAIN = (
    b"acfqp:v075-batched-observation-transcript-step:v1"
)
BATCH_SIGNING_DOMAIN = b"acfqp:v075-signed-observation-batch:v1"

DOMAIN_TAGS = {
    "request": "acfqp:v075-batched-observation-request:v1",
    "outcome": "acfqp:v075-batched-public-outcome:v1",
    "batch": "acfqp:v075-signed-observation-batch:v1",
    "public_verification": (
        "acfqp:v075-batched-observation-public-verification:v1"
    ),
    "sequence_verification": (
        "acfqp:v075-batched-observation-sequence-verification:v1"
    ),
    "private_replay_verification": (
        "acfqp:v075-batched-observation-private-replay-verification:v1"
    ),
}

if len(DOMAIN_TAGS) != len(set(DOMAIN_TAGS.values())):  # pragma: no cover
    raise RuntimeError("V0-075 batched-observer domains must be unique")


class V075BatchedObserverInvariantViolation(ValueError):
    """A request, batch, signature, sequence, or replay invariant failed."""


def _fail(message: str) -> None:
    raise V075BatchedObserverInvariantViolation(message)


def _hash(role: str, payload: Mapping[str, Any]) -> str:
    try:
        return hashlib.sha256(
            DOMAIN_TAGS[role].encode("utf-8")
            + b"\x00"
            + canonical_json_bytes(dict(payload))
        ).hexdigest()
    except (KeyError, TypeError, ValueError) as error:
        raise V075BatchedObserverInvariantViolation(str(error)) from error


def _cid(value: Any, field_name: str) -> str:
    try:
        return parse_content_id(value)
    except ValueError as error:
        raise V075BatchedObserverInvariantViolation(
            f"{field_name} must be one lowercase SHA-256 content ID"
        ) from error


def _fdoc(value: Fraction) -> dict[str, int]:
    if type(value) is not Fraction:
        _fail("batched observer arithmetic must use exact Fraction")
    return {
        "numerator": value.numerator,
        "denominator": value.denominator,
    }


def _fraction_from_document(value: Any, field_name: str) -> Fraction:
    if type(value) is Fraction:
        return value
    if (
        type(value) is not dict
        or frozenset(value) != {"numerator", "denominator"}
        or type(value["numerator"]) is not int
        or type(value["denominator"]) is not int
        or value["denominator"] <= 0
    ):
        _fail(f"{field_name} is not one exact rational")
    result = Fraction(value["numerator"], value["denominator"])
    if _fdoc(result) != value:
        _fail(f"{field_name} is not reduced canonical rational form")
    return result


def _exact_mapping(
    value: Any,
    keys: set[str],
    *,
    field_name: str,
) -> dict[str, Any]:
    if (
        type(value) is not dict
        or frozenset(value) != frozenset(keys)
        or any(type(key) is not str for key in value)
    ):
        _fail(f"{field_name} field set is missing or contains unknown fields")
    return value


def _strict_load(raw: bytes, *, field_name: str) -> dict[str, Any]:
    if type(raw) is not bytes or len(raw) > MAX_CANONICAL_BATCH_BYTES:
        _fail(f"{field_name} must be capped canonical bytes")
    try:
        value = loads_canonical_json(raw)
    except Phase3EIdentityError as error:
        raise V075BatchedObserverInvariantViolation(str(error)) from error
    if type(value) is not dict or canonical_json_bytes(value) != raw:
        _fail(f"{field_name} is not one canonical object")
    return value


class V075BatchAuthorityScopeV1(str, Enum):
    PRODUCTION_OPEN = "PRODUCTION_OPEN"
    CONSTRUCTION_ONLY = "CONSTRUCTION_ONLY"


def _scope_from_binding(
    binding: observer.V075ObserverOpenAuthorityBindingV1,
) -> V075BatchAuthorityScopeV1:
    if (
        type(binding) is not observer.V075ObserverOpenAuthorityBindingV1
    ):
        _fail("batch session has a foreign observer-open binding")
    if (
        binding.scope
        is observer.V075ObserverOpenAuthorityScopeV1.PRODUCTION_OPEN
    ):
        return V075BatchAuthorityScopeV1.PRODUCTION_OPEN
    if (
        binding.scope
        is observer.V075ObserverOpenAuthorityScopeV1.CONSTRUCTION_ONLY
    ):
        return V075BatchAuthorityScopeV1.CONSTRUCTION_ONLY
    _fail("batch session has an unknown authority scope")
    raise AssertionError("unreachable")


_REQUEST_ISSUER = object()


@dataclass(frozen=True, slots=True)
class V075BatchedObservationRequestV1:
    _issuer: object
    session_public_id: str
    observer_open_binding: observer.V075ObserverOpenAuthorityBindingV1
    stream_identity: graph.V075TransitionStreamIdentityV1
    authority_scope: V075BatchAuthorityScopeV1
    accepted_draw_start: int
    accepted_draw_count: int
    accepted_draw_cap: int
    _request_id: str = field(init=False, repr=False)

    def __post_init__(self) -> None:
        _cid(self.session_public_id, "batch request observer session")
        end = self.accepted_draw_start + self.accepted_draw_count - 1
        if (
            self._issuer is not _REQUEST_ISSUER
            or type(self.observer_open_binding)
            is not observer.V075ObserverOpenAuthorityBindingV1
            or type(self.stream_identity)
            is not graph.V075TransitionStreamIdentityV1
            or self.stream_identity.namespace
            != self.observer_open_binding.namespace
            or type(self.authority_scope) is not V075BatchAuthorityScopeV1
            or self.authority_scope
            is not _scope_from_binding(self.observer_open_binding)
            or type(self.accepted_draw_start) is not int
            or self.accepted_draw_start <= 0
            or type(self.accepted_draw_count) is not int
            or not 0 < self.accepted_draw_count
            <= MAX_BATCH_ACCEPTED_DRAW_COUNT
            or type(self.accepted_draw_cap) is not int
            or not 0 < self.accepted_draw_cap <= MAX_ACCEPTED_DRAW_CAP
            or end > self.accepted_draw_cap
        ):
            _fail("batch request is untyped, over-cap, or authority-transplanted")
        object.__setattr__(
            self,
            "_request_id",
            _hash("request", self._payload()),
        )

    @property
    def accepted_draw_end(self) -> int:
        return self.accepted_draw_start + self.accepted_draw_count - 1

    @property
    def request_id(self) -> str:
        return self._request_id

    def _payload(self) -> dict[str, Any]:
        stream = self.stream_identity
        return {
            "schema": "acfqp.v075_batched_observation_request.v1",
            "schema_version": SCHEMA_VERSION,
            "profile_key": PROFILE_KEY,
            "observer_session_public_id": self.session_public_id,
            "observer_open_binding_id": self.observer_open_binding.binding_id,
            "authority_scope": self.authority_scope.value,
            "target_tape_namespace_id": stream.target_tape_namespace_id,
            "environment_commitment_id": (
                self.observer_open_binding.namespace.environment_commitment
                .commitment_id
            ),
            "context_id": stream.context_id,
            "context_ordinal": (
                stream.row_binding.context.replicate_ordinal
            ),
            "row_binding_id": stream.row_binding_id,
            "catalogue_id": stream.catalogue_id,
            "stream_id": stream.stream_id,
            "pairing_group_id": stream.pairing_group_id,
            "support_epoch_id": stream.support_epoch_id,
            "observer_epoch_index": stream.observer_epoch_index,
            "lane": stream.lane.value,
            "arm": stream.arm,
            "accepted_draw_start": self.accepted_draw_start,
            "accepted_draw_count": self.accepted_draw_count,
            "accepted_draw_end": self.accepted_draw_end,
            "accepted_draw_cap": self.accepted_draw_cap,
            "request_nonce_allowed": False,
            "reroll_allowed": False,
            "private_material_serialized": False,
        }

    def to_document(self) -> dict[str, Any]:
        return {
            **self._payload(),
            "observer_open_binding": self.observer_open_binding.to_document(),
            "stream_identity": self.stream_identity.to_document(),
            "request_id": self.request_id,
        }

    @property
    def canonical_bytes(self) -> bytes:
        return canonical_json_bytes(self.to_document())


def _issue_request(
    *,
    session: observer.V075PrivateObserverSessionV1,
    stream_identity: graph.V075TransitionStreamIdentityV1,
    accepted_draw_start: int,
    accepted_draw_count: int,
    accepted_draw_cap: int,
) -> V075BatchedObservationRequestV1:
    if (
        type(session) is not observer.V075PrivateObserverSessionV1
        or type(stream_identity)
        is not graph.V075TransitionStreamIdentityV1
        or stream_identity.namespace != session.authority_binding.namespace
    ):
        _fail("batch request issuer requires an exact session and stream")
    return V075BatchedObservationRequestV1(
        _REQUEST_ISSUER,
        session.session_public_id,
        session.authority_binding,
        stream_identity,
        _scope_from_binding(session.authority_binding),
        accepted_draw_start,
        accepted_draw_count,
        accepted_draw_cap,
    )


@dataclass(frozen=True, slots=True)
class V075BatchedPublicOutcomeAggregateV1:
    next_ranks: tuple[int, ...]
    failure: bool
    terminal: bool
    spawn_cell: int
    spawn_rank: int
    realized_row_reward: Fraction
    count: int
    reward_sum: Fraction

    def __post_init__(self) -> None:
        if (
            type(self.next_ranks) is not tuple
            or not self.next_ranks
            or any(type(rank) is not int or rank < 0 for rank in self.next_ranks)
            or type(self.failure) is not bool
            or type(self.terminal) is not bool
            or type(self.spawn_cell) is not int
            or self.spawn_cell < 0
            or type(self.spawn_rank) is not int
            or self.spawn_rank <= 0
            or type(self.realized_row_reward) is not Fraction
            or self.realized_row_reward < 0
            or type(self.count) is not int
            or self.count <= 0
            or type(self.reward_sum) is not Fraction
            or self.reward_sum != self.realized_row_reward * self.count
        ):
            _fail("public outcome aggregate is malformed")

    def _outcome_payload(self) -> dict[str, Any]:
        return {
            "schema": "acfqp.v075_batched_public_outcome.v1",
            "schema_version": SCHEMA_VERSION,
            "next_ranks": list(self.next_ranks),
            "failure": self.failure,
            "terminal": self.terminal,
            "spawn_cell": self.spawn_cell,
            "spawn_rank": self.spawn_rank,
            "realized_row_reward": _fdoc(self.realized_row_reward),
        }

    @property
    def outcome_id(self) -> str:
        return _hash("outcome", self._outcome_payload())

    def to_document(self) -> dict[str, Any]:
        return {
            **self._outcome_payload(),
            "outcome_id": self.outcome_id,
            "count": self.count,
            "reward_sum": _fdoc(self.reward_sum),
        }


def _sample_leaf_payload(sample: H2GraphSampleV1) -> dict[str, Any]:
    if type(sample) is not H2GraphSampleV1:
        _fail("transcript leaf requires one exact sample")
    return {
        "schema": "acfqp.v075_batched_observation_transcript_leaf.v1",
        "schema_version": SCHEMA_VERSION,
        "accepted_draw_index": sample.accepted_draw_index,
        "random_word_start_index": sample.random_word_start_index,
        "random_words": list(sample.random_words),
        "next_ranks": list(sample.next_state.ranks),
        "failure": sample.failure,
        "terminal": sample.terminal,
        "spawn_cell": sample.spawn_cell,
        "spawn_rank": sample.spawn_rank,
        "realized_row_reward": _fdoc(sample.realized_row_reward),
    }


class _StreamingBatchAccumulatorV1:
    __slots__ = (
        "_accepted_count",
        "_failure_count",
        "_first_random_word_index",
        "_outcomes",
        "_random_word_count",
        "_rejection_count",
        "_request",
        "_reward_sum",
        "_terminal_count",
        "_transcript_state",
    )

    def __init__(self, request: V075BatchedObservationRequestV1) -> None:
        if type(request) is not V075BatchedObservationRequestV1:
            _fail("batch accumulator requires one exact request")
        self._request = request
        self._accepted_count = 0
        self._failure_count = 0
        self._terminal_count = 0
        self._random_word_count = 0
        self._rejection_count = 0
        self._reward_sum = Fraction(0)
        self._first_random_word_index: int | None = None
        self._outcomes: dict[
            tuple[Any, ...],
            tuple[int, Fraction],
        ] = {}
        self._transcript_state = hashlib.sha256(
            TRANSCRIPT_INITIAL_DOMAIN
            + b"\x00"
            + request.request_id.encode("ascii")
        ).digest()

    def append(self, sample: H2GraphSampleV1) -> None:
        expected_index = (
            self._request.accepted_draw_start + self._accepted_count
        )
        if (
            type(sample) is not H2GraphSampleV1
            or sample.accepted_draw_index != expected_index
            or (
                self._first_random_word_index is not None
                and sample.random_word_start_index
                != self._first_random_word_index + self._random_word_count
            )
        ):
            _fail("batch sample interval is gapped, overlapped, or reordered")
        if self._first_random_word_index is None:
            self._first_random_word_index = sample.random_word_start_index
        key = (
            sample.next_state.ranks,
            sample.failure,
            sample.terminal,
            sample.spawn_cell,
            sample.spawn_rank,
            sample.realized_row_reward,
        )
        prior_count, prior_reward = self._outcomes.get(
            key,
            (0, Fraction(0)),
        )
        self._outcomes[key] = (
            prior_count + 1,
            prior_reward + sample.realized_row_reward,
        )
        self._accepted_count += 1
        self._failure_count += int(sample.failure)
        self._terminal_count += int(sample.terminal)
        self._random_word_count += sample.random_word_count
        self._rejection_count += sample.rejection_count
        self._reward_sum += sample.realized_row_reward
        leaf = hashlib.sha256(
            TRANSCRIPT_LEAF_DOMAIN
            + b"\x00"
            + canonical_json_bytes(_sample_leaf_payload(sample))
        ).digest()
        self._transcript_state = hashlib.sha256(
            TRANSCRIPT_STEP_DOMAIN
            + b"\x00"
            + self._transcript_state
            + b"\x00"
            + leaf
        ).digest()

    def finish(self) -> "_BatchFactsV1":
        if (
            self._accepted_count != self._request.accepted_draw_count
            or self._first_random_word_index is None
        ):
            _fail("batch accumulator did not cover the complete request")
        outcomes = tuple(
            sorted(
                (
                    V075BatchedPublicOutcomeAggregateV1(
                        key[0],
                        key[1],
                        key[2],
                        key[3],
                        key[4],
                        key[5],
                        count,
                        reward,
                    )
                    for key, (count, reward) in self._outcomes.items()
                ),
                key=lambda item: item.outcome_id,
            )
        )
        return _BatchFactsV1(
            outcomes,
            self._reward_sum,
            self._failure_count,
            self._terminal_count,
            self._random_word_count,
            self._rejection_count,
            self._first_random_word_index,
            self._first_random_word_index + self._random_word_count,
            self._transcript_state.hex(),
        )


@dataclass(frozen=True, slots=True)
class _BatchFactsV1:
    outcomes: tuple[V075BatchedPublicOutcomeAggregateV1, ...]
    reward_sum: Fraction
    failure_count: int
    terminal_count: int
    random_word_count: int
    rejection_count: int
    first_random_word_index: int
    next_random_word_index: int
    transcript_commitment: str

    def __post_init__(self) -> None:
        _cid(self.transcript_commitment, "batch transcript commitment")
        accepted = sum(item.count for item in self.outcomes)
        if (
            type(self.outcomes) is not tuple
            or not self.outcomes
            or any(
                type(item) is not V075BatchedPublicOutcomeAggregateV1
                for item in self.outcomes
            )
            or tuple(item.outcome_id for item in self.outcomes)
            != tuple(sorted(item.outcome_id for item in self.outcomes))
            or len({item.outcome_id for item in self.outcomes})
            != len(self.outcomes)
            or type(self.reward_sum) is not Fraction
            or self.reward_sum
            != sum(
                (item.reward_sum for item in self.outcomes),
                Fraction(0),
            )
            or type(self.failure_count) is not int
            or self.failure_count
            != sum(item.count for item in self.outcomes if item.failure)
            or type(self.terminal_count) is not int
            or self.terminal_count
            != sum(item.count for item in self.outcomes if item.terminal)
            or type(self.random_word_count) is not int
            or self.random_word_count < accepted
            or type(self.rejection_count) is not int
            or self.rejection_count != self.random_word_count - accepted
            or type(self.first_random_word_index) is not int
            or self.first_random_word_index <= 0
            or self.next_random_word_index
            != self.first_random_word_index + self.random_word_count
        ):
            _fail("batch aggregate facts do not reconcile")


def _batch_payload(
    *,
    request: V075BatchedObservationRequestV1,
    facts: _BatchFactsV1,
) -> dict[str, Any]:
    return {
        "schema": "acfqp.v075_signed_observation_batch.v1",
        "schema_version": SCHEMA_VERSION,
        "proposed_contract_version": PROPOSED_CONTRACT_VERSION,
        "profile_key": PROFILE_KEY,
        "request_id": request.request_id,
        "observer_session_public_id": request.session_public_id,
        "observer_open_binding_id": request.observer_open_binding.binding_id,
        "authority_scope": request.authority_scope.value,
        "target_tape_namespace_id": (
            request.stream_identity.target_tape_namespace_id
        ),
        "environment_commitment_id": (
            request.observer_open_binding.namespace.environment_commitment
            .commitment_id
        ),
        "observer_signer_key_id": (
            request.observer_open_binding.namespace.signer_registry
            .observer_evidence_key.key_id
        ),
        "context_id": request.stream_identity.context_id,
        "row_binding_id": request.stream_identity.row_binding_id,
        "stream_id": request.stream_identity.stream_id,
        "arm": request.stream_identity.arm,
        "observer_epoch_index": (
            request.stream_identity.observer_epoch_index
        ),
        "accepted_draw_start": request.accepted_draw_start,
        "accepted_draw_count": request.accepted_draw_count,
        "accepted_draw_end": request.accepted_draw_end,
        "accepted_draw_cap": request.accepted_draw_cap,
        "outcome_aggregate_ids": [
            item.outcome_id for item in facts.outcomes
        ],
        "reward_sum": _fdoc(facts.reward_sum),
        "failure_count": facts.failure_count,
        "terminal_count": facts.terminal_count,
        "random_word_count": facts.random_word_count,
        "rejection_count": facts.rejection_count,
        "first_random_word_index": facts.first_random_word_index,
        "next_random_word_index": facts.next_random_word_index,
        "transcript_commitment": facts.transcript_commitment,
        "transcript_scheme": (
            "SHA256_DOMAIN_SEPARATED_ORDERED_SAMPLE_HASH_CHAIN_V1"
        ),
        "per_draw_records_serialized": False,
        "individual_random_words_serialized": False,
        "private_law_serialized": False,
        "private_salt_serialized": False,
        "private_kernel_serialized": False,
    }


def batched_observation_signing_bytes_v1(
    *,
    request: V075BatchedObservationRequestV1,
    facts: _BatchFactsV1,
) -> bytes:
    if (
        type(request) is not V075BatchedObservationRequestV1
        or type(facts) is not _BatchFactsV1
    ):
        _fail("batch signing request/facts are not exact typed objects")
    return (
        BATCH_SIGNING_DOMAIN
        + b"\x00"
        + canonical_json_bytes(_batch_payload(request=request, facts=facts))
    )


@dataclass(frozen=True, slots=True)
class V075SignedBatchedObservationV1:
    request: V075BatchedObservationRequestV1
    outcomes: tuple[V075BatchedPublicOutcomeAggregateV1, ...]
    reward_sum: Fraction
    failure_count: int
    terminal_count: int
    random_word_count: int
    rejection_count: int
    first_random_word_index: int
    next_random_word_index: int
    transcript_commitment: str
    observer_signature_hex: str

    def __post_init__(self) -> None:
        if type(self.request) is not V075BatchedObservationRequestV1:
            _fail("signed batch requires one exact request")
        facts = self.facts
        message = batched_observation_signing_bytes_v1(
            request=self.request,
            facts=facts,
        )
        try:
            signature_verified = (
                public.verify_rsa_pkcs1_v1_5_sha256_signature_v1(
                    public_key=(
                        self.request.observer_open_binding.namespace
                        .signer_registry.observer_evidence_key
                    ),
                    message=message,
                    signature_hex=self.observer_signature_hex,
                )
            )
        except (
            public.V075PublicCampaignAuthorityInvariantViolation,
            TypeError,
            ValueError,
        ) as error:
            raise V075BatchedObserverInvariantViolation(
                "batch observer signature is malformed"
            ) from error
        if not signature_verified:
            _fail("batch observer signature is invalid or transplanted")
        if sum(item.count for item in self.outcomes) != (
            self.request.accepted_draw_count
        ):
            _fail("signed batch aggregate omits or duplicates accepted draws")

    @property
    def facts(self) -> _BatchFactsV1:
        return _BatchFactsV1(
            self.outcomes,
            self.reward_sum,
            self.failure_count,
            self.terminal_count,
            self.random_word_count,
            self.rejection_count,
            self.first_random_word_index,
            self.next_random_word_index,
            self.transcript_commitment,
        )

    @property
    def batch_id(self) -> str:
        return _hash(
            "batch",
            {
                **_batch_payload(request=self.request, facts=self.facts),
                "observer_signature_hex": self.observer_signature_hex,
                "observer_signature_verified": True,
            },
        )

    def to_document(self) -> dict[str, Any]:
        return {
            **_batch_payload(request=self.request, facts=self.facts),
            "request": self.request.to_document(),
            "outcomes": [item.to_document() for item in self.outcomes],
            "observer_signature_hex": self.observer_signature_hex,
            "observer_signature_verified": True,
            "batch_id": self.batch_id,
        }

    @property
    def canonical_bytes(self) -> bytes:
        return canonical_json_bytes(self.to_document())


_BATCH_SESSION_ISSUER = object()


class V075PrivateBatchedObserverSessionV1:
    """Exclusive streaming adapter over one exact private observer session."""

    __slots__ = (
        "_accepted_cap_by_stream",
        "_aggregate_support_evidence_by_id",
        "_batches",
        "_executed_request_ids",
        "_failed",
        "_issued_validation_row_ids",
        "_session",
    )

    def __init__(
        self,
        *,
        session: observer.V075PrivateObserverSessionV1,
        issuer: object,
    ) -> None:
        if (
            issuer is not _BATCH_SESSION_ISSUER
            or type(session) is not observer.V075PrivateObserverSessionV1
            or session.journal_entries
            or getattr(session, "_closed", True)
        ):
            _fail(
                "batched adapter requires one open, unused exact observer session"
            )
        self._session = session
        self._accepted_cap_by_stream: dict[str, int] = {}
        self._aggregate_support_evidence_by_id: dict[
            str,
            graph.V075BatchAggregateSupportEvidenceV1,
        ] = {}
        self._executed_request_ids: set[str] = set()
        self._issued_validation_row_ids: set[str] = set()
        self._batches: list[V075SignedBatchedObservationV1] = []
        self._failed = False

    @property
    def session_public_id(self) -> str:
        return self._session.session_public_id

    @property
    def authority_scope(self) -> V075BatchAuthorityScopeV1:
        return _scope_from_binding(self._session.authority_binding)

    @property
    def batches(self) -> tuple[V075SignedBatchedObservationV1, ...]:
        return tuple(self._batches)

    def freeze_aggregate_support_evidence_v1(
        self,
        *,
        discovery_batch: V075SignedBatchedObservationV1,
        selected_outcome_ids: tuple[str, ...],
    ) -> tuple[graph.V075BatchAggregateSupportEvidenceV1, ...]:
        """Freeze signed support from aggregate DISCOVERY outcomes.

        No individual draw is reconstructed or assigned an index.  A
        subsequent VALIDATION request is accepted only when its support epoch
        contains evidence frozen through this exact session before that
        request was issued.
        """

        if (
            type(discovery_batch) is not V075SignedBatchedObservationV1
            or discovery_batch not in self._batches
            or discovery_batch.request.session_public_id
            != self._session.session_public_id
            or discovery_batch.request.observer_open_binding
            != self._session.authority_binding
            or discovery_batch.request.stream_identity.lane
            is not graph.V075ObservationLaneV1.DISCOVERY
            or discovery_batch.request.stream_identity.observer_epoch_index
            != 0
            or type(selected_outcome_ids) is not tuple
            or not selected_outcome_ids
            or selected_outcome_ids
            != tuple(sorted(set(selected_outcome_ids)))
            or len(selected_outcome_ids)
            > graph.MAX_SUPPORT_MEMBERS_PER_ROW
        ):
            _fail(
                "aggregate support freeze requires one completed DISCOVERY "
                "batch and canonical observed outcomes"
            )
        row = discovery_batch.request.stream_identity.row_binding
        if row.row_binding_id in self._issued_validation_row_ids:
            _fail("aggregate support cannot change after validation issuance")
        outcome_by_id = {
            item.outcome_id: item for item in discovery_batch.outcomes
        }
        if not set(selected_outcome_ids) <= set(outcome_by_id):
            _fail("aggregate support selected an unobserved DISCOVERY outcome")
        signer = getattr(self._session, "_signer", None)
        expected_key = (
            self._session.authority_binding.namespace.signer_registry
            .observer_evidence_key
        )
        evidence: list[graph.V075BatchAggregateSupportEvidenceV1] = []
        observed_state_ids: set[str] = set()
        for outcome_id in selected_outcome_ids:
            outcome = outcome_by_id[outcome_id]
            observed_state = graph.V075SymbolicGraphStateV1(
                row.context,
                outcome.next_ranks,
                outcome.failure,
            )
            if observed_state.state_id in observed_state_ids:
                _fail(
                    "aggregate support cannot multiply one projected state "
                    "through spawn-identity aliases"
                )
            observed_state_ids.add(observed_state.state_id)
            message = (
                graph.batch_aggregate_support_evidence_signing_bytes_v1(
                    namespace=self._session.authority_binding.namespace,
                    row_binding=row,
                    observed_state=observed_state,
                    source_observer_epoch_index=0,
                    discovery_request_id=discovery_batch.request.request_id,
                    discovery_batch_id=discovery_batch.batch_id,
                    discovery_outcome_id=outcome.outcome_id,
                    discovery_outcome_count=outcome.count,
                )
            )
            try:
                signature = observer._sign(
                    signer=signer,
                    expected_key=expected_key,
                    message=message,
                )
                item = graph.bind_batch_aggregate_support_evidence_v1(
                    namespace=self._session.authority_binding.namespace,
                    row_binding=row,
                    observed_state=observed_state,
                    source_observer_epoch_index=0,
                    discovery_request_id=discovery_batch.request.request_id,
                    discovery_batch_id=discovery_batch.batch_id,
                    discovery_outcome_id=outcome.outcome_id,
                    discovery_outcome_count=outcome.count,
                    observer_signature_hex=signature,
                )
            except (
                observer.V075PrivateObserverBoundaryInvariantViolation,
                graph.V075PublicGraphSemanticsInvariantViolation,
            ) as error:
                raise V075BatchedObserverInvariantViolation(
                    str(error)
                ) from error
            evidence.append(item)
        result = tuple(sorted(evidence, key=lambda item: item.evidence_id))
        for item in result:
            self._aggregate_support_evidence_by_id[item.evidence_id] = item
        return result

    def issue_request_v1(
        self,
        *,
        stream_identity: graph.V075TransitionStreamIdentityV1,
        accepted_draw_start: int,
        accepted_draw_count: int,
        accepted_draw_cap: int,
    ) -> V075BatchedObservationRequestV1:
        if (
            self._failed
            or self._session.journal_entries
            or getattr(self._session, "_closed", True)
            or type(stream_identity)
            is not graph.V075TransitionStreamIdentityV1
        ):
            _fail("per-draw and batched observer paths cannot be mixed")
        is_validation = (
            stream_identity.lane
            is graph.V075ObservationLaneV1.VALIDATION
        )
        if is_validation:
            evidence = stream_identity.pairing_authority.support_chain.leaf.evidence
            if (
                not evidence
                or any(
                    type(item)
                    is not graph.V075BatchAggregateSupportEvidenceV1
                    or self._aggregate_support_evidence_by_id.get(
                        item.evidence_id
                    )
                    != item
                    or item.row_binding != stream_identity.row_binding
                    or item.source_observer_epoch_index != 0
                    for item in evidence
                )
            ):
                _fail(
                    "validation request lacks pre-frozen batch aggregate "
                    "DISCOVERY support"
                )
        request = _issue_request(
            session=self._session,
            stream_identity=stream_identity,
            accepted_draw_start=accepted_draw_start,
            accepted_draw_count=accepted_draw_count,
            accepted_draw_cap=accepted_draw_cap,
        )
        prior_cap = self._accepted_cap_by_stream.get(stream_identity.stream_id)
        if prior_cap is not None and prior_cap != accepted_draw_cap:
            _fail("one stream cannot reroll by changing its accepted-draw cap")
        stream = getattr(self._session, "_streams", {}).get(
            stream_identity.stream_id
        )
        current = 0 if stream is None else stream.accepted_draw_count
        if accepted_draw_start != current + 1:
            _fail("batch request start is gapped, overlapping, or stale")
        if is_validation:
            self._issued_validation_row_ids.add(
                stream_identity.row_binding_id
            )
        return request

    def execute_request_v1(
        self,
        request: V075BatchedObservationRequestV1,
    ) -> V075SignedBatchedObservationV1:
        if (
            type(request) is not V075BatchedObservationRequestV1
            or request.session_public_id != self._session.session_public_id
            or request.observer_open_binding != self._session.authority_binding
            or request.authority_scope is not self.authority_scope
            or request.request_id in self._executed_request_ids
            or self._failed
            or self._session.journal_entries
            or getattr(self._session, "_closed", True)
        ):
            _fail("batch request is reused, transplanted, or mixed with records")
        stream_identity = request.stream_identity
        prior_cap = self._accepted_cap_by_stream.get(stream_identity.stream_id)
        if prior_cap is not None and prior_cap != request.accepted_draw_cap:
            _fail("batch execution cap changed after its first request")
        kernels = getattr(self._session, "_kernels", None)
        streams = getattr(self._session, "_streams", None)
        if type(kernels) is not dict or type(streams) is not dict:
            _fail("private observer implementation changed under batch adapter")
        kernel = kernels.get(stream_identity.context_id)
        if type(kernel) is not H2GraphKernelV1:
            _fail("batch adapter lacks the bound private context kernel")
        stream = streams.get(stream_identity.stream_id)
        if stream is None:
            try:
                stream = DeterministicH2GraphStreamV1(
                    kernel=kernel,
                    state=(
                        stream_identity.row_binding.catalogue.state
                        .to_kernel_state()
                    ),
                    action=H2GraphActionV1(*stream_identity.action),
                    remaining_horizon=(
                        stream_identity.row_binding.remaining_horizon
                    ),
                    seed=stream_identity.seed,
                )
            except H2GraphTransitionInvariantViolation as error:
                raise V075BatchedObserverInvariantViolation(str(error)) from error
            streams[stream_identity.stream_id] = stream
        if stream.accepted_draw_count + 1 != request.accepted_draw_start:
            _fail("batch execution interval is gapped, overlapping, or stale")
        # Once the deterministic tape advances, any exception must close this
        # adapter rather than allowing an unaccounted retry.
        self._failed = True
        accumulator = _StreamingBatchAccumulatorV1(request)
        for _index in range(request.accepted_draw_count):
            accumulator.append(stream.draw())
        facts = accumulator.finish()
        signer = getattr(self._session, "_signer", None)
        expected_key = (
            request.observer_open_binding.namespace.signer_registry
            .observer_evidence_key
        )
        try:
            signature = observer._sign(
                signer=signer,
                expected_key=expected_key,
                message=batched_observation_signing_bytes_v1(
                    request=request,
                    facts=facts,
                ),
            )
        except observer.V075PrivateObserverBoundaryInvariantViolation as error:
            raise V075BatchedObserverInvariantViolation(str(error)) from error
        result = V075SignedBatchedObservationV1(
            request,
            facts.outcomes,
            facts.reward_sum,
            facts.failure_count,
            facts.terminal_count,
            facts.random_word_count,
            facts.rejection_count,
            facts.first_random_word_index,
            facts.next_random_word_index,
            facts.transcript_commitment,
            signature,
        )
        self._accepted_cap_by_stream[stream_identity.stream_id] = (
            request.accepted_draw_cap
        )
        self._executed_request_ids.add(request.request_id)
        self._batches.append(result)
        self._failed = False
        return result


def wrap_v075_production_batched_observer_session_v1(
    session: observer.V075PrivateObserverSessionV1,
) -> V075PrivateBatchedObserverSessionV1:
    if (
        type(session) is not observer.V075PrivateObserverSessionV1
        or _scope_from_binding(session.authority_binding)
        is not V075BatchAuthorityScopeV1.PRODUCTION_OPEN
    ):
        _fail("production batch wrapper rejects construction observer sessions")
    return V075PrivateBatchedObserverSessionV1(
        session=session,
        issuer=_BATCH_SESSION_ISSUER,
    )


def wrap_v075_construction_batched_observer_session_v1(
    session: observer.V075PrivateObserverSessionV1,
) -> V075PrivateBatchedObserverSessionV1:
    if (
        type(session) is not observer.V075PrivateObserverSessionV1
        or _scope_from_binding(session.authority_binding)
        is not V075BatchAuthorityScopeV1.CONSTRUCTION_ONLY
    ):
        _fail("construction batch wrapper rejects production observer sessions")
    return V075PrivateBatchedObserverSessionV1(
        session=session,
        issuer=_BATCH_SESSION_ISSUER,
    )


def freeze_v075_batch_aggregate_support_evidence_v1(
    *,
    batched_session: V075PrivateBatchedObserverSessionV1,
    discovery_batch: V075SignedBatchedObservationV1,
    selected_outcome_ids: tuple[str, ...],
) -> tuple[graph.V075BatchAggregateSupportEvidenceV1, ...]:
    """Public entry point for pre-validation aggregate support freezing."""

    if type(batched_session) is not V075PrivateBatchedObserverSessionV1:
        _fail("aggregate support freezer requires one exact batch session")
    return batched_session.freeze_aggregate_support_evidence_v1(
        discovery_batch=discovery_batch,
        selected_outcome_ids=selected_outcome_ids,
    )


def load_v075_batched_observation_request_v1(
    *,
    raw: bytes,
    batched_session: V075PrivateBatchedObserverSessionV1,
    stream_identity: graph.V075TransitionStreamIdentityV1,
) -> V075BatchedObservationRequestV1:
    """Load one parent-issued canonical request before any child draw."""

    if (
        type(batched_session) is not V075PrivateBatchedObserverSessionV1
        or type(stream_identity)
        is not graph.V075TransitionStreamIdentityV1
    ):
        _fail("batch request loader rejects duck session/stream authorities")
    item = _strict_load(raw, field_name="batched observation request")
    expected_keys = {
        "schema",
        "schema_version",
        "profile_key",
        "observer_session_public_id",
        "observer_open_binding_id",
        "authority_scope",
        "target_tape_namespace_id",
        "environment_commitment_id",
        "context_id",
        "context_ordinal",
        "row_binding_id",
        "catalogue_id",
        "stream_id",
        "pairing_group_id",
        "support_epoch_id",
        "observer_epoch_index",
        "lane",
        "arm",
        "accepted_draw_start",
        "accepted_draw_count",
        "accepted_draw_end",
        "accepted_draw_cap",
        "request_nonce_allowed",
        "reroll_allowed",
        "private_material_serialized",
        "observer_open_binding",
        "stream_identity",
        "request_id",
    }
    _exact_mapping(item, expected_keys, field_name="batched observation request")
    if (
        item["schema"] != "acfqp.v075_batched_observation_request.v1"
        or item["schema_version"] != SCHEMA_VERSION
        or item["profile_key"] != PROFILE_KEY
    ):
        _fail("batched observation request schema changed")
    request = batched_session.issue_request_v1(
        stream_identity=stream_identity,
        accepted_draw_start=item["accepted_draw_start"],
        accepted_draw_count=item["accepted_draw_count"],
        accepted_draw_cap=item["accepted_draw_cap"],
    )
    if request.canonical_bytes != raw:
        _fail("batched request is stale, transplanted, or noncanonical")
    return request


def _outcome_from_document(
    value: Any,
) -> V075BatchedPublicOutcomeAggregateV1:
    item = _exact_mapping(
        value,
        {
            "schema",
            "schema_version",
            "next_ranks",
            "failure",
            "terminal",
            "spawn_cell",
            "spawn_rank",
            "realized_row_reward",
            "outcome_id",
            "count",
            "reward_sum",
        },
        field_name="batch outcome aggregate",
    )
    if (
        item["schema"] != "acfqp.v075_batched_public_outcome.v1"
        or item["schema_version"] != SCHEMA_VERSION
        or type(item["next_ranks"]) is not list
        or any(type(rank) is not int for rank in item["next_ranks"])
        or type(item["failure"]) is not bool
        or type(item["terminal"]) is not bool
    ):
        _fail("batch outcome aggregate schema changed")
    result = V075BatchedPublicOutcomeAggregateV1(
        tuple(item["next_ranks"]),
        item["failure"],
        item["terminal"],
        item["spawn_cell"],
        item["spawn_rank"],
        _fraction_from_document(
            item["realized_row_reward"],
            "outcome reward",
        ),
        item["count"],
        _fraction_from_document(item["reward_sum"], "outcome reward sum"),
    )
    if result.outcome_id != _cid(item["outcome_id"], "outcome ID"):
        _fail("batch outcome content identity mismatch")
    return result


def load_v075_signed_batched_observation_v1(
    *,
    raw: bytes,
    request: V075BatchedObservationRequestV1,
) -> V075SignedBatchedObservationV1:
    """Strict loader; request identity is a typed authority, not a string."""

    if type(request) is not V075BatchedObservationRequestV1:
        _fail("batch loader requires the exact typed request")
    item = _strict_load(raw, field_name="signed observation batch")
    expected_keys = {
        "schema",
        "schema_version",
        "proposed_contract_version",
        "profile_key",
        "request_id",
        "observer_session_public_id",
        "observer_open_binding_id",
        "authority_scope",
        "target_tape_namespace_id",
        "environment_commitment_id",
        "observer_signer_key_id",
        "context_id",
        "row_binding_id",
        "stream_id",
        "arm",
        "observer_epoch_index",
        "accepted_draw_start",
        "accepted_draw_count",
        "accepted_draw_end",
        "accepted_draw_cap",
        "outcome_aggregate_ids",
        "reward_sum",
        "failure_count",
        "terminal_count",
        "random_word_count",
        "rejection_count",
        "first_random_word_index",
        "next_random_word_index",
        "transcript_commitment",
        "transcript_scheme",
        "per_draw_records_serialized",
        "individual_random_words_serialized",
        "private_law_serialized",
        "private_salt_serialized",
        "private_kernel_serialized",
        "request",
        "outcomes",
        "observer_signature_hex",
        "observer_signature_verified",
        "batch_id",
    }
    _exact_mapping(item, expected_keys, field_name="signed observation batch")
    if (
        item["schema"] != "acfqp.v075_signed_observation_batch.v1"
        or item["schema_version"] != SCHEMA_VERSION
        or item["proposed_contract_version"] != PROPOSED_CONTRACT_VERSION
        or item["profile_key"] != PROFILE_KEY
        or canonical_json_bytes(item["request"]) != request.canonical_bytes
        or item["request_id"] != request.request_id
        or type(item["outcomes"]) is not list
        or item["observer_signature_verified"] is not True
    ):
        _fail("signed observation batch request/schema binding changed")
    outcomes = tuple(_outcome_from_document(value) for value in item["outcomes"])
    result = V075SignedBatchedObservationV1(
        request,
        outcomes,
        _fraction_from_document(item["reward_sum"], "batch reward sum"),
        item["failure_count"],
        item["terminal_count"],
        item["random_word_count"],
        item["rejection_count"],
        item["first_random_word_index"],
        item["next_random_word_index"],
        item["transcript_commitment"],
        item["observer_signature_hex"],
    )
    if (
        result.canonical_bytes != raw
        or result.batch_id != _cid(item["batch_id"], "batch ID")
    ):
        _fail("signed observation batch differs from semantic reconstruction")
    return result


_PUBLIC_VERIFIER_ISSUER = object()


@dataclass(frozen=True, slots=True)
class V075BatchedObservationPublicVerificationV1:
    _issuer: object
    request_id: str
    batch_id: str
    observer_open_binding_id: str
    accepted_draw_count: int
    _verification_id: str = field(init=False, repr=False)

    def __post_init__(self) -> None:
        for value, name in (
            (self.request_id, "publicly verified request"),
            (self.batch_id, "publicly verified batch"),
            (
                self.observer_open_binding_id,
                "publicly verified observer binding",
            ),
        ):
            _cid(value, name)
        if (
            self._issuer is not _PUBLIC_VERIFIER_ISSUER
            or type(self.accepted_draw_count) is not int
            or self.accepted_draw_count <= 0
        ):
            _fail("public batch verification was caller-minted")
        object.__setattr__(
            self,
            "_verification_id",
            _hash("public_verification", self._payload()),
        )

    @property
    def verification_id(self) -> str:
        return self._verification_id

    def _payload(self) -> dict[str, Any]:
        return {
            "schema": (
                "acfqp.v075_batched_observation_public_verification.v1"
            ),
            "schema_version": SCHEMA_VERSION,
            "request_id": self.request_id,
            "batch_id": self.batch_id,
            "observer_open_binding_id": self.observer_open_binding_id,
            "accepted_draw_count": self.accepted_draw_count,
            "verification_result": (
                "SIGNATURE_AND_INTERNAL_RECONCILIATION_VERIFIED"
            ),
            "private_replay_claimed": False,
            "private_material_serialized": False,
        }

    def to_document(self) -> dict[str, Any]:
        return {**self._payload(), "verification_id": self.verification_id}


def verify_v075_signed_batched_observation_v1(
    claimed: V075SignedBatchedObservationV1,
) -> V075BatchedObservationPublicVerificationV1:
    if type(claimed) is not V075SignedBatchedObservationV1:
        _fail("public batch verifier rejects duck-typed batches")
    replayed = V075SignedBatchedObservationV1(
        claimed.request,
        claimed.outcomes,
        claimed.reward_sum,
        claimed.failure_count,
        claimed.terminal_count,
        claimed.random_word_count,
        claimed.rejection_count,
        claimed.first_random_word_index,
        claimed.next_random_word_index,
        claimed.transcript_commitment,
        claimed.observer_signature_hex,
    )
    # Both objects are exact frozen typed graphs.  ``request_id`` binds the
    # complete request graph, while ``batch_id`` binds that request plus every
    # aggregate fact and the verified signature.  Re-serializing the deeply
    # nested public namespace twice here adds no semantic check beyond exact
    # object equality and content-ID equality.
    if replayed != claimed or replayed.batch_id != claimed.batch_id:
        _fail("signed batch differs from public semantic replay")
    return V075BatchedObservationPublicVerificationV1(
        _PUBLIC_VERIFIER_ISSUER,
        claimed.request.request_id,
        claimed.batch_id,
        claimed.request.observer_open_binding.binding_id,
        claimed.request.accepted_draw_count,
    )


_SEQUENCE_VERIFIER_ISSUER = object()


@dataclass(frozen=True, slots=True)
class V075BatchedObservationSequenceVerificationV1:
    _issuer: object
    session_public_id: str
    stream_id: str
    batch_ids: tuple[str, ...]
    accepted_draw_count: int
    accepted_draw_cap: int
    _verification_id: str = field(init=False, repr=False)

    def __post_init__(self) -> None:
        _cid(self.session_public_id, "sequence observer session")
        _cid(self.stream_id, "sequence stream")
        for value in self.batch_ids:
            _cid(value, "sequence batch")
        if (
            self._issuer is not _SEQUENCE_VERIFIER_ISSUER
            or type(self.batch_ids) is not tuple
            or not self.batch_ids
            or len(set(self.batch_ids)) != len(self.batch_ids)
            or type(self.accepted_draw_count) is not int
            or self.accepted_draw_count <= 0
            or type(self.accepted_draw_cap) is not int
            or self.accepted_draw_count > self.accepted_draw_cap
        ):
            _fail("batch sequence verification is malformed or caller-minted")
        object.__setattr__(
            self,
            "_verification_id",
            _hash("sequence_verification", self._payload()),
        )

    @property
    def verification_id(self) -> str:
        return self._verification_id

    def _payload(self) -> dict[str, Any]:
        return {
            "schema": (
                "acfqp.v075_batched_observation_sequence_verification.v1"
            ),
            "schema_version": SCHEMA_VERSION,
            "observer_session_public_id": self.session_public_id,
            "stream_id": self.stream_id,
            "batch_ids": list(self.batch_ids),
            "accepted_draw_start": 1,
            "accepted_draw_count": self.accepted_draw_count,
            "accepted_draw_end": self.accepted_draw_count,
            "accepted_draw_cap": self.accepted_draw_cap,
            "verification_result": "CONTIGUOUS_PREFIX_VERIFIED",
            "gaps": 0,
            "overlaps": 0,
            "reorders": 0,
        }

    def to_document(self) -> dict[str, Any]:
        return {**self._payload(), "verification_id": self.verification_id}


def verify_v075_batched_observation_sequence_v1(
    batches: tuple[V075SignedBatchedObservationV1, ...],
) -> V075BatchedObservationSequenceVerificationV1:
    if (
        type(batches) is not tuple
        or not batches
        or any(type(item) is not V075SignedBatchedObservationV1 for item in batches)
    ):
        _fail("batch sequence requires a nonempty exact typed tuple")
    first = batches[0].request
    expected_start = 1
    for batch in batches:
        verify_v075_signed_batched_observation_v1(batch)
        request = batch.request
        if (
            request.session_public_id != first.session_public_id
            or request.observer_open_binding != first.observer_open_binding
            or request.stream_identity != first.stream_identity
            or request.authority_scope is not first.authority_scope
            or request.accepted_draw_cap != first.accepted_draw_cap
            or request.accepted_draw_start != expected_start
        ):
            _fail(
                "batch sequence is gapped, overlapping, reordered, "
                "or context/arm transplanted"
            )
        expected_start = request.accepted_draw_end + 1
    return V075BatchedObservationSequenceVerificationV1(
        _SEQUENCE_VERIFIER_ISSUER,
        first.session_public_id,
        first.stream_identity.stream_id,
        tuple(item.batch_id for item in batches),
        expected_start - 1,
        first.accepted_draw_cap,
    )


_CONSTRUCTION_ENV_ISSUER = object()


@dataclass(frozen=True, slots=True, repr=False)
class V075ConstructionBatchReplayEnvironmentFixtureV1:
    _issuer: object = field(repr=False)
    namespace: public.V075PublicTargetTapeNamespaceV1 = field(repr=False)
    private_salt: bytes = field(repr=False)
    private_environment: tuple[
        tuple[tuple[int, Fraction], ...], ...
    ] = field(repr=False)

    def __post_init__(self) -> None:
        if (
            self._issuer is not _CONSTRUCTION_ENV_ISSUER
            or type(self.namespace)
            is not public.V075PublicTargetTapeNamespaceV1
            or type(self.private_salt) is not bytes
            or type(self.private_environment) is not tuple
        ):
            _fail("construction replay environment was caller-minted")
        try:
            reveal = public.verify_opaque_environment_reveal_v1(
                commitment=self.namespace.environment_commitment,
                secret_salt=self.private_salt,
                secret_laws=self.private_environment,
            )
        except public.V075PublicCampaignAuthorityInvariantViolation as error:
            raise V075BatchedObserverInvariantViolation(str(error)) from error
        if not reveal.matched:
            _fail("construction replay environment does not match commitment")

    def __repr__(self) -> str:
        return (
            "<V075ConstructionBatchReplayEnvironmentFixtureV1 "
            "private_material=redacted>"
        )

    def __reduce_ex__(self, _protocol: int) -> Any:
        raise TypeError("construction private replay material is not serializable")


def issue_v075_construction_batch_replay_environment_fixture_v1(
    *,
    namespace: public.V075PublicTargetTapeNamespaceV1,
    private_salt: bytes,
    private_environment: Iterable[Iterable[tuple[int, Fraction]]],
) -> V075ConstructionBatchReplayEnvironmentFixtureV1:
    if type(namespace) is not public.V075PublicTargetTapeNamespaceV1:
        _fail("construction replay fixture requires one exact namespace")
    try:
        environment = tuple(tuple(law) for law in private_environment)
    except TypeError as error:
        raise V075BatchedObserverInvariantViolation(str(error)) from error
    return V075ConstructionBatchReplayEnvironmentFixtureV1(
        _CONSTRUCTION_ENV_ISSUER,
        namespace,
        private_salt,
        environment,
    )


_PRIVATE_REPLAY_ISSUER = object()


@dataclass(frozen=True, slots=True)
class V075BatchedObservationPrivateReplayVerificationV1:
    _issuer: object
    batch_id: str
    request_id: str
    observer_open_binding_id: str
    authority_scope: V075BatchAuthorityScopeV1
    replayed_draw_count: int
    _verification_id: str = field(init=False, repr=False)

    def __post_init__(self) -> None:
        for value, name in (
            (self.batch_id, "private-replayed batch"),
            (self.request_id, "private-replayed request"),
            (
                self.observer_open_binding_id,
                "private-replayed observer binding",
            ),
        ):
            _cid(value, name)
        if (
            self._issuer is not _PRIVATE_REPLAY_ISSUER
            or type(self.authority_scope) is not V075BatchAuthorityScopeV1
            or type(self.replayed_draw_count) is not int
            or self.replayed_draw_count <= 0
        ):
            _fail("private replay attestation was caller-minted")
        object.__setattr__(
            self,
            "_verification_id",
            _hash("private_replay_verification", self._payload()),
        )

    @property
    def verification_id(self) -> str:
        return self._verification_id

    def _payload(self) -> dict[str, Any]:
        return {
            "schema": (
                "acfqp.v075_batched_observation_private_replay_verification.v1"
            ),
            "schema_version": SCHEMA_VERSION,
            "batch_id": self.batch_id,
            "request_id": self.request_id,
            "observer_open_binding_id": self.observer_open_binding_id,
            "authority_scope": self.authority_scope.value,
            "replayed_draw_count": self.replayed_draw_count,
            "verification_result": "EXACT_PRIVATE_INTERVAL_REPLAY_MATCH",
            "private_law_serialized": False,
            "private_salt_serialized": False,
            "private_kernel_serialized": False,
            "individual_samples_serialized": False,
        }

    def to_document(self) -> dict[str, Any]:
        return {**self._payload(), "verification_id": self.verification_id}


def _replay_batch_from_binding(
    *,
    claimed: V075SignedBatchedObservationV1,
    binding: observer.V075ObserverOpenAuthorityBindingV1,
    private_salt: bytes,
    private_environment: tuple[
        tuple[tuple[int, Fraction], ...], ...
    ],
) -> V075BatchedObservationPrivateReplayVerificationV1:
    if (
        type(claimed) is not V075SignedBatchedObservationV1
        or type(binding) is not observer.V075ObserverOpenAuthorityBindingV1
        or claimed.request.observer_open_binding != binding
        or claimed.request.authority_scope is not _scope_from_binding(binding)
    ):
        _fail("private replay batch/authority binding was transplanted")
    try:
        reveal = public.verify_opaque_environment_reveal_v1(
            commitment=binding.namespace.environment_commitment,
            secret_salt=private_salt,
            secret_laws=private_environment,
        )
    except public.V075PublicCampaignAuthorityInvariantViolation as error:
        raise V075BatchedObserverInvariantViolation(str(error)) from error
    if not reveal.matched:
        _fail("private replay environment does not match opaque commitment")
    context = claimed.request.stream_identity.row_binding.context
    contexts = binding.namespace.family.replicate_contexts
    if context != contexts[context.replicate_ordinal]:
        _fail("private replay context/order binding changed")
    try:
        kernel = H2GraphKernelV1(
            context.topology,
            context.rank_cap,
            context.horizon,
            private_environment[context.replicate_ordinal],
        )
        stream_identity = claimed.request.stream_identity
        stream = DeterministicH2GraphStreamV1(
            kernel=kernel,
            state=stream_identity.row_binding.catalogue.state.to_kernel_state(),
            action=H2GraphActionV1(*stream_identity.action),
            remaining_horizon=stream_identity.row_binding.remaining_horizon,
            seed=stream_identity.seed,
        )
        accumulator = _StreamingBatchAccumulatorV1(claimed.request)
        for accepted_index in range(1, claimed.request.accepted_draw_end + 1):
            sample = stream.draw()
            if accepted_index >= claimed.request.accepted_draw_start:
                accumulator.append(sample)
        replayed = accumulator.finish()
    except (
        H2GraphTransitionInvariantViolation,
        IndexError,
    ) as error:
        raise V075BatchedObserverInvariantViolation(str(error)) from error
    if replayed != claimed.facts:
        _fail("signed batch aggregates differ from exact private replay")
    verify_v075_signed_batched_observation_v1(claimed)
    return V075BatchedObservationPrivateReplayVerificationV1(
        _PRIVATE_REPLAY_ISSUER,
        claimed.batch_id,
        claimed.request.request_id,
        binding.binding_id,
        claimed.request.authority_scope,
        claimed.request.accepted_draw_count,
    )


def verify_v075_production_batched_observation_private_replay_v1(
    *,
    claimed: V075SignedBatchedObservationV1,
    authority: "V075ProductionOpenAuthorityV1",
    namespace: public.V075PublicTargetTapeNamespaceV1,
    private_salt: bytes,
    private_environment: private_env.V075PrivateGeneratedEnvironmentV1,
) -> V075BatchedObservationPrivateReplayVerificationV1:
    """Production replay accepts only generated private environment authority."""

    if (
        type(private_environment)
        is not private_env.V075PrivateGeneratedEnvironmentV1
        or type(namespace) is not public.V075PublicTargetTapeNamespaceV1
        or private_environment.family != namespace.family
    ):
        _fail("production batch replay rejects construction/duck environments")
    try:
        binding = observer._require_production_open_binding(
            authority=authority,
            namespace=namespace,
        )
    except observer.V075PrivateObserverBoundaryInvariantViolation as error:
        raise V075BatchedObserverInvariantViolation(str(error)) from error
    return _replay_batch_from_binding(
        claimed=claimed,
        binding=binding,
        private_salt=private_salt,
        private_environment=(
            private_environment.secret_laws_for_commitment()
        ),
    )


def verify_v075_construction_batched_observation_private_replay_v1(
    *,
    claimed: V075SignedBatchedObservationV1,
    authority: observer.V075ConstructionOnlyObserverOpenAuthorityFixtureV1,
    private_environment: V075ConstructionBatchReplayEnvironmentFixtureV1,
) -> V075BatchedObservationPrivateReplayVerificationV1:
    """Construction replay is exact-type separated from production."""

    if (
        type(authority)
        is not observer.V075ConstructionOnlyObserverOpenAuthorityFixtureV1
        or type(private_environment)
        is not V075ConstructionBatchReplayEnvironmentFixtureV1
        or private_environment.namespace != authority.namespace
    ):
        _fail("construction batch replay rejects production/duck authorities")
    try:
        binding = observer._require_construction_open_binding(authority=authority)
    except observer.V075PrivateObserverBoundaryInvariantViolation as error:
        raise V075BatchedObserverInvariantViolation(str(error)) from error
    return _replay_batch_from_binding(
        claimed=claimed,
        binding=binding,
        private_salt=private_environment.private_salt,
        private_environment=private_environment.private_environment,
    )


__all__ = [
    "MAX_ACCEPTED_DRAW_CAP",
    "MAX_BATCH_ACCEPTED_DRAW_COUNT",
    "PROFILE_KEY",
    "V075BatchAuthorityScopeV1",
    "V075BatchedObservationPrivateReplayVerificationV1",
    "V075BatchedObservationPublicVerificationV1",
    "V075BatchedObservationRequestV1",
    "V075BatchedObservationSequenceVerificationV1",
    "V075BatchedObserverInvariantViolation",
    "V075BatchedPublicOutcomeAggregateV1",
    "V075ConstructionBatchReplayEnvironmentFixtureV1",
    "V075PrivateBatchedObserverSessionV1",
    "V075SignedBatchedObservationV1",
    "freeze_v075_batch_aggregate_support_evidence_v1",
    "issue_v075_construction_batch_replay_environment_fixture_v1",
    "load_v075_batched_observation_request_v1",
    "load_v075_signed_batched_observation_v1",
    "verify_v075_batched_observation_sequence_v1",
    "verify_v075_construction_batched_observation_private_replay_v1",
    "verify_v075_production_batched_observation_private_replay_v1",
    "verify_v075_signed_batched_observation_v1",
    "wrap_v075_construction_batched_observer_session_v1",
    "wrap_v075_production_batched_observer_session_v1",
]
